api/urls.py
from django.urls import re_path, include
from rest_framework import routers 
from blog.models import Post
from api.views import UserViewSet,\
APITagViewSet,APIPostViewSet, APICategoryViewSet, APISubCategoryViewSet,APIProfileViewSet
from dj_rest_auth.views import PasswordResetConfirmView


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'tags', APITagViewSet)
router.register(r'posts', APIPostViewSet)
router.register(r'categories', APICategoryViewSet)
router.register(r'subcategories', APISubCategoryViewSet)
router.register(r'profile', APIProfileViewSet)



urlpatterns = [
    re_path(r'^', include(router.urls)),
    re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path(r'^rest-auth/', include('dj_rest_auth.urls')),
    re_path(r'^rest-auth/registration/', include('dj_rest_auth.registration.urls'))
    re_path(r'^v1/rest-auth/password/reset/confirm/<uuid>/<token>/', PasswordResetConfirmView.as_view(), name = "password-reset-confirm")

    # re_path(r'^posts/',APIPostListCreateView.as_view(), name = "list"),
    # re_path(r'^post/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/$', APIPostDetailView.as_view(), name = 'detail'),
    # re_path(r'^post/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/edit/$', APIPostUpdateDestroyDetailView.as_view(), name = 'edit'),
    # re_path(r'^tags/', APITagListCreateView.as_view(), name = 'list'),
    # re_path(r'^tag/(?P<pk>[-\d]+)/', APITagDetailView.as_view(), name = 'detail'),
    # re_path(r'^tag/(?P<pk>[-\d]+)/edit/$', APITagEditView.as_view(), name = 'edit'),
    
]

blog/urls.py
from .import views
from django.urls import re_path, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap 
from blog.sitemaps import StaticViewSitemap,PostSitemap
sitemaps = {
    'static': StaticViewSitemap,
    'post':PostSitemap
}

app_name = 'blog'

urlpatterns = [
    re_path(r'^list/$', views.PostListView.as_view(), name = 'list'), 
    re_path(r'^create/$', views.PostCreateView.as_view(), name = 'create'), 
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/delete/$', views.PostDeleteView.as_view(), name = 'delete'),
    re_path(r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/edit/$', views.PostUpdateView.as_view(), name='update'),
    re_path(r'^(?P<slug>[-\w]+)/detail/$', views.PostDetailView.as_view(), name = 'detail'),
    re_path(r'^sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
   

insurance/urls.py

from django.contrib import admin
from django.urls import re_path, include
from insurance import views
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    re_path(r'^api/', include('api.urls')),
    re_path(r'^', include('accounts.urls',namespace='accounts')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^blog/', include('blog.urls')),
    re_path(r'^location/', include('location.urls')),
    re_path(r'^search/', include('search.urls')),
    re_path(r'^dashboard/', include('dashboard.urls')),
    re_path(r'^tag/', include('tag.urls')),
    re_path(r'^ticket/', include('tickets.urls')),
    re_path(r'^category/', include('category.urls')),
    re_path(r'^contact/', include('contact.urls')),
    re_path(r'^user/', include('users.urls')),
    re_path(r'^', include('frontend.urls',namespace='frontend')),
    re_path(r'^subcategory/', include('category.subcaturls')),
    re_path(r'^social-auth/', include('social_django.urls', namespace='social')),
    re_path(r'^', include('django.contrib.auth.urls')),
    re_path(r'^__debug__/', include('debug_toolbar.urls')),
    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='backend/accounts/login.html'), name='login'),
    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^accounts/reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='backend/accounts/password_reset.html',
            html_email_template_name='backend/accounts/password_reset_email.html',
            email_template_name='backend/accounts/password_reset_email.html',
            subject_template_name='backend/accounts/password_reset_subject.txt'
        ),
        name='password_reset'),
    re_path(r'^accounts/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='backend/accounts/password_reset_done.html'),
        name='password_reset_done'),
    re_path(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='backend/accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    re_path(r'^accounts/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='backend/accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    re_path(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='backend/accounts/password_change_done.html'),
        name='password_change_done'),
    re_path(r'^.*\.*', views.pages, name='pages'),   
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

blog/models.py
import uuid
from django.db import models
from django.conf import settings
from django.urls.base import reverse
from painless.models.mixins import OrganizedMixin
from painless.models.managers import PostPublishedManager
from tag.models import Tag
from category.models import SubCategory
from painless.models.choices import PostStatus
from ckeditor.fields import RichTextField


status = PostStatus(is_charfield = False)

class Post(OrganizedMixin):
    uid = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name = 'posts', on_delete = models.CASCADE)
    summary = models.CharField(max_length = 128)
    banner = models.ImageField(upload_to = 'blog/%Y/%m/%d', null = True, blank = True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.PROTECT, related_name = 'posts')
    tag = models.ManyToManyField(Tag, related_name = 'post',  blank = True)
    content = RichTextField(blank=True,null=True)

    objects = models.Manager()
    condition = PostPublishedManager()

    class Meta:
        ordering = ['-published_at', 'title']
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        get_latest_by = ['-published_at']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"slug": self.slug})
    
    

blog/forms.py
from django import forms
from blog.models import Post
from ckeditor.fields import RichTextField
from ckeditor.widgets import CKEditorWidget


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Post
        exclude=("slug",)


    def clean_title(self):
        data = self.cleaned_data.get('title')
        if len(data) < 5:
            raise forms.ValidationError("length of title is less than Five!")
        return data

    def clean_summary(self):
        data = self.cleaned_data.get('summary')
        if len(data) < 20:
            raise forms.ValidationError("the length of summary is less than 20 letter!")
        return data


    def clean_published(self):
        data = self.cleaned_data.get('published_at')
        if not data == "DD/MM/YYYY":
            raise forms.ValidationError("format is not true")
        return data
    

blog/views.py

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.db.models.query_utils import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls.base import reverse_lazy
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from blog.models import Post
from tag.models import Tag
from blog.forms import PostForm
from django.utils import timezone
from category.models import Category, SubCategory
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from django.http.response import HttpResponse, HttpResponseRedirect
from django.template import loader
from django import template


User = get_user_model()

# @method_decorator(cache_page(60 * 60 * 24), name='dispatch')
class PostListView(LoginRequiredMixin, ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'backend/blog/list.html'
    paginate_by = 10

    # it is for pagination
    def get_queryset(self):
        filter_val = self.request.GET.get("filter", "")
        order_by = self.request.GET.get("orderby", "pk")
        if filter_val != "":
            post = Post.objects.filter(Q(title__contains=filter_val) | Q(
                description__contains=filter_val)).order_by(order_by)
        else:
            post = Post.objects.all().order_by(order_by)
        return post

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context["filter"] = self.request.GET.get("filter", "")
        context["orderby"] = self.request.GET.get("orderby", "pk")
        context["all_table_fields"] = Post._meta.get_fields()
        return context


class PostCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    context_object_name = "form"
    template_name = "backend/blog/create.html"
    success_url = reverse_lazy('blog:list')
    success_message = "Post Added Successfully!"
    permission_required = "post.create_post"

    def handle_no_permission(self):
        messages.warning(
            self.request, "You dont have permission to this page please signin with superuser!")
        return redirect("dashboard:home")

    def get(self, request, *args, **kwargs):
        categories = Category.objects.filter(status = "1")
        tags = Tag.objects.filter(status="1").order_by(
            "-created").prefetch_related('post')
        users = User.objects.all()
        categories_list = []
        for category in categories:
            sub_category = SubCategory.objects.filter(category_id=category.id)
            categories_list.append(
                {"category": category, "sub_category": sub_category})
        return render(request, "backend/blog/create.html", {"categories": categories_list, "tags": tags, 'users': users})


class PostDeleteView(SuccessMessageMixin, PermissionRequiredMixin, DeleteView):
    model = Post
    permission_required = "post.delete_post"
    template_name = 'backend/blog/list.html'
    success_url = reverse_lazy('blog:list')
    success_message = "Post Delete successfully"

    def handle_no_permission(self):
        messages.warning(
            self.request, "You dont have permission to this page please signin with superuser!")
        return redirect("dashboard:home")

    def get(self, request, *args, **kwargs):
        pk = kwargs.get("pk")
        if pk is not None:
            post_object = Post.objects.get_queryset().filter(pk=pk)
            if post_object is not None:
                post_object.delete()
                messages.success(request, 'Your Post was updated.')
                return redirect('blog:list')
        return redirect('backend/blog/list.html')


class PostUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):

    def handle_no_permission(self):
        messages.warning(
            self.request, "You dont have permission to this page please signin with superuser!")
        return redirect("dashboard:home")

    def get(self, request, *args, **kwargs):
        post_id = kwargs['pk']
        categories = Category.objects.all()
        tags = Tag.objects.filter(status="1").order_by(
            "-created").prefetch_related('post')
        posts = Post.objects.all()
        users = User.objects.all()
        post = Post.objects.get(pk=post_id)
        categories_list = []
        for category in categories:
            sub_category = SubCategory.objects.filter(category_id=category.id)
            categories_list.append(
                {"category": category, "sub_category": sub_category})
        return render(request, "backend/blog/edit.html", {"categories": categories_list, "post": post, "tags": tags, "posts": posts, 'users': users})

    def post(self, request, *args, **kwargs):
        instance = get_object_or_404(Post, pk=kwargs['pk'])
        if request.method == 'POST':
            form = PostForm(request.POST, request.FILES or None,
                            instance=instance)
            if form.is_valid():
                form = form.save(commit=False)
                form.user = request.user
                form.updated = timezone.now()
                form.save()
                messages.success(request,
                                 "Post updated successfull!")
                return redirect("blog:list")
        else:
            form = PostForm()
        return render(request, 'backend/blog/edit.html',
                      {'form': form}
                      )


class PostDetailView(DetailView):
    template_name = 'frontend/landing/detail.html'
    context_object_name = "post"
    model = Post

    def get_object(self, queryset=None):
        post = Post.objects.get(slug=self.kwargs.get("slug"))
        return post


templates/backend/blog/create.html
{% extends "backend/layouts/base.html" %} {% block title %}Create Tag
{%endblock%} {% block stylesheets %}{% endblock stylesheets %} {% block content %}

<div class="py-4">
  <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
    <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
      <li class="breadcrumb-item">
        <a href="#">
          <svg
            class="icon icon-xxs"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
            ></path>
          </svg>
        </a>
      </li>
      <li class="breadcrumb-item"><a href="#">Tables</a></li>
      <li class="breadcrumb-item active" aria-current="page">Post tables</li>
    </ol>
  </nav>
</div>

<div class="card border-0 shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      {% if form.non_field_errors %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {% for error in form.non_field_errors %}
        <button
          type="button"
          class="btn-close btn-sm"
          data-bs-dismiss="alert"
          aria-label="Close"
        ></button>
        <div {% if message.posts %} class="{{ message.post }}" {% endif %}>
          {{ error }}
        </div>
        {% endfor %}
      </div>
      {% endif %}
      <form
        id="post_form"
        method="POST"
        action=""
        enctype="multipart/form-data"
      >
        {% csrf_token %}
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">
              <label for="{{ form.title.id_for_label }}"
                >title</label
              >
              <input
                class="form-control"
                name="title"
                placeholder="Name"
                id="title"
              />
              {% for error in form.errors.title %}
              <p class="text-danger">{{ error }}</p>
              {% endfor %}
            </div>
            <div class="col-lg-6">
              <label>published_at</label>
              <div class="input-group">
                <span class="input-group-text">
                  <svg
                    class="icon icon-xs"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z"
                      clip-rule="evenodd"
                    ></path>
                  </svg>
                </span>
                <input
                  data-datepicker=""
                  class="form-control"
                  id="birthday"
                  type="text"
                  name="published_at"
                  placeholder="dd/mm/yyyy"
                  required
                />
              </div>
              {% for error in form.errors.title %}
              <p class="text-danger">{{ error.title }}</p>
              {% endfor %}
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-lg-12">
              <label>summary</label>
              <input
              class="form-control"
              name="summary"
              placeholder="summary"
              />
              {% for error in form.errors.summary %}
              <p class="text-danger">{{ error }}</p>
              {% endfor %}
            </div>
          </div>
          
          <br>
          <div class="row">
            <div class="col-lg-12">
              <label>content</label>
              <textarea name="content" id="content" class="form-control">&lt;p&gt;Initial editor content.&lt;/p&gt;</textarea>

              {% for error in form.errors.content %}
              <p class="text-danger">{{ error }}</p>
              {% endfor %}
            </div>
          </div>

          <div class="row mt-4">
            <div class="col-lg-6">
              <label>Merchant User</label>
              <select class="form-control" name="author">
                {% for user in users %}
                <option value="{{ user.id }}">{{ user.email }}</option>
                {% endfor %}
              </select>
              {% for error in form.errors.title %}
              <p class="text-danger">{{ error.title }}</p>
              {% endfor %}
            </div>

            <div class="col-lg-6">
              <label>Category</label>
              <select name="subcategory" class="form-control">
                {% for category in categories %}
                <optgroup label="{{ category.category.title }}">
                  {% for sub_cat in category.sub_category %}
                  <option value="{{ sub_cat.id }}">{{ sub_cat.title }}</option>
                  {% endfor %}
                </optgroup>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="media_div">
            <div class="row media_div_row first_media">
              <div class="col-lg-4">
                <label>Tag</label>

                <select
                  class="form-select"
                  multiple
                  aria-label="multiple select example"
                  name="tag"
                >
                  {% for tag in tags %}
                  <option value="{{ tag.id }}">{{ tag.title }}</option>
                  {% endfor %}
                </select>
                {% for error in form.errors.title %}
                <p class="text-danger">{{ error }}</p>
                {% endfor %}
              </div>
              <div class="col-lg-4">
                <label>status</label>
                <select name="status" class="form-control media_type">
                  <option value="0">draft</option>
                  <option value="1">published</option>
                </select>
              </div>
            </div>
          </div>
          <div class="col-lg-4 mb-4">
            <label>banner</label>
            <input
              type="file"
              name="banner"
              class="form-control select_media"
            />
          </div>
          <div class="row">
            <button type="submit" class="btn btn-primary btn-block submit_btn">
              ADD POST
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock content %}
 {% block javascripts %} 
<script src="https://cdn.ckeditor.com/4.17.2/standard/ckeditor.js"></script>
 
 <script>
  CKEDITOR.replace( 'content' );
</script>
{% endblock javascripts %}

templates/backend/blog/list.html
{% extends "backend/layouts/base.html" %} 
{% block title %}List Post{% endblock%}

{% block stylesheets %}{% endblock stylesheets %} {% block content %}
{% if messages %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {% for m in messages %}
    <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
    <div {% if message.posts %} class="{{ message.post }}"{% endif %}>{{ m }}</div>
    {% endfor %}
</div>
{% endif %}
<div class="py-4">
  <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
    <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
      <li class="breadcrumb-item">
        <a href="#">
          <svg
            class="icon icon-xxs"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
            ></path>
          </svg>
        </a>
      </li>
      <li class="breadcrumb-item"><a href="#">Tables</a></li>
      <li class="breadcrumb-item active" aria-current="page">
        Post tables
      </li>
    </ol>
  </nav>
</div>

<div class="card border-0 shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-centered table-nowrap mb-0 rounded">
        <thead class="thead-light">
          <tr>
            <th class="border-0 rounded-start">#</th>
            <th class="border-0">Image</th>
            <th class="border-0">Title</th>
            <th class="border-0">Slug</th>
            <th class="border-0">Category</th>
            <th class="border-0">Status</th>
            <th class="border-0">Created</th>
            <th class="border-0">Updated</th>
            <th class="border-0">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for post in posts %}
          {% if user.is_superuser %}
            <tr>
            <td><a href="#" class="text-primary fw-bold">
            {{ forloop.counter }}
            </a>
          </td>
          {% if post.banner %}
          <td><img src="..{{ post.banner.url }}" class = "rounded-circle" width=70 /></td>
          {% endif %}
          <td>{{ post.title}}</td>
          <td>{{ post.slug}}</td>
            <td>{{ post.subcategory.category }}</td>
            <td>{% if post.status == 1 %} Published {% else %} Draft {% endif %}</td>
            <td>{{ post.updated }}</td>
            <td class="text-success">
              <div class="d-flex align-items-center">
                <svg
                  class="icon icon-xs me-1"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fill-rule="evenodd"
                    d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
                <span class="fw-bold">{{ post.created }}</span>
              </div>
            </td>
            {% if request.user.is_authenticated%} 
            <td>
             <a href="{% url "blog:update" post.pk %}"><img src="https://img.icons8.com/bubbles/30/000000/edit.png"/></a> 
              <form method = "POST" action="{% url "subcategory:list" %}">
                {% csrf_token %}
                <a href="{% url "blog:delete" post.pk %}"><img src="https://img.icons8.com/cute-clipart/25/000000/trash.png"/></a>
              </form>
            </td>
            {% endif %}
          </tr>
          {% endif %}
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="card-body">
      <nav aria-label="Page navigation example">
        <ul class="pagination">
          {% if page_obj.has_previous %}
              <li class="page-item"><a class="page-link" href="{% url 'blog:list' %}' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.previous_page_number }}">Previous</a></li>
          {% else %}
              <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
          {% endif %}
          {% for i in paginator.page_range %}
                  <li class="page-item {% if i == page_obj.number %}active{% endif %}"><a class="page-link" href="{% url 'blog:list' %}' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ i }}">{{ i }}</a></li>
          {% endfor %}
          {% if page_obj.has_next %}
              <li class="page-item"><a class="page-link" href="{% url 'blog:list' %}' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.next_page_number }}">Next</a></li>
          {% else %}
              <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
          {% endif %}
  </div>
  </div>
</div>

{% endblock content %}
{% block javascripts %}{% endblock javascripts %}