api/urls.py
from django.urls import re_path, include
from rest_framework import routers 
from blog.models import Post
from api.views import UserViewSet,\
APITagViewSet,APIPostViewSet, APICategoryViewSet, APISubCategoryViewSet,APIProfileViewSet
from dj_rest_auth.views import PasswordResetConfirmView


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'tags', APITagViewSet)
router.register(r'posts', APIPostViewSet)
router.register(r'categories', APICategoryViewSet)
router.register(r'subcategories', APISubCategoryViewSet)
router.register(r'profile', APIProfileViewSet)



urlpatterns = [
    re_path(r'^', include(router.urls)),
    re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path(r'^rest-auth/', include('dj_rest_auth.urls')),
    re_path(r'^rest-auth/registration/', include('dj_rest_auth.registration.urls'))
    re_path(r'^v1/rest-auth/password/reset/confirm/<uuid>/<token>/', PasswordResetConfirmView.as_view(), name = "password-reset-confirm")

    # re_path(r'^posts/',APIPostListCreateView.as_view(), name = "list"),
    # re_path(r'^post/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/$', APIPostDetailView.as_view(), name = 'detail'),
    # re_path(r'^post/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12})/edit/$', APIPostUpdateDestroyDetailView.as_view(), name = 'edit'),
    # re_path(r'^tags/', APITagListCreateView.as_view(), name = 'list'),
    # re_path(r'^tag/(?P<pk>[-\d]+)/', APITagDetailView.as_view(), name = 'detail'),
    # re_path(r'^tag/(?P<pk>[-\d]+)/edit/$', APITagEditView.as_view(), name = 'edit'),
    
]

dashboard/urls.py
from django.urls import re_path
from .import views
from django.contrib.auth import views as auth_views


app_name = 'dashboard'
urlpatterns = [
    re_path(r'home/',views.DashboardView.as_view(), name = 'home'), 
    re_path(r'^settings/password/$', 
        auth_views.PasswordChangeView.as_view(template_name='backend/accounts/password_change.html'),
        name='password_change'),
    
    
]

insurance/urls.py

from django.contrib import admin
from django.urls import re_path, include
from insurance import views
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    re_path(r'^api/', include('api.urls')),
    re_path(r'^', include('accounts.urls',namespace='accounts')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^blog/', include('blog.urls')),
    re_path(r'^location/', include('location.urls')),
    re_path(r'^search/', include('search.urls')),
    re_path(r'^dashboard/', include('dashboard.urls')),
    re_path(r'^tag/', include('tag.urls')),
    re_path(r'^ticket/', include('tickets.urls')),
    re_path(r'^category/', include('category.urls')),
    re_path(r'^contact/', include('contact.urls')),
    re_path(r'^user/', include('users.urls')),
    re_path(r'^', include('frontend.urls',namespace='frontend')),
    re_path(r'^subcategory/', include('category.subcaturls')),
    re_path(r'^social-auth/', include('social_django.urls', namespace='social')),
    re_path(r'^', include('django.contrib.auth.urls')),
    re_path(r'^__debug__/', include('debug_toolbar.urls')),
    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='backend/accounts/login.html'), name='login'),
    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^accounts/reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='backend/accounts/password_reset.html',
            html_email_template_name='backend/accounts/password_reset_email.html',
            email_template_name='backend/accounts/password_reset_email.html',
            subject_template_name='backend/accounts/password_reset_subject.txt'
        ),
        name='password_reset'),
    re_path(r'^accounts/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='backend/accounts/password_reset_done.html'),
        name='password_reset_done'),
    re_path(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='backend/accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    re_path(r'^accounts/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='backend/accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    re_path(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='backend/accounts/password_change_done.html'),
        name='password_change_done'),
    re_path(r'^.*\.*', views.pages, name='pages'),   
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

tickets/urls.py
from . import views
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static


app_name = 'tickets'

urlpatterns = [

    # create new ticket
    re_path(r'^ticket/new/$', views.ticket_create_view, name='ticket_create'),
    # edit ticket
    re_path(r'^ticket/edit/(?P<pk>\d+)/$', views.ticket_edit_view, name='ticket_edit'),
    # view ticket
    re_path(r'^ticket-detail/(?P<pk>\d+)/$', views.ticket_detail_view, name='ticket_detail'),
    # create new followup
    re_path(r'^followup/new/$', views.followup_create_view, name='followup_new'),
    # edit followup
    re_path(r'^followup/edit/(?P<pk>\d+)/$', views.followup_edit_view, name='followup_edit'),
    # create new attachment
    re_path(r'^attachment/new/$', views.attachment_create_view, name='attachment_new'),
    re_path(r'^my-tickets/$', views.my_tickets_view, name='my-tickets'),
    re_path(r'^list/$', views.all_tickets_view, name='list'),
    # re_path(r'^archive/$', views.archive_view, name='archive'),

 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from .import views
from django.urls import re_path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user'

urlpatterns = [
    re_path(r'^generate/', views.GenerateRandomUserView.as_view(), name='generate'),
    re_path(r'^create/', views.ProfileView.as_view(), name='create'),
    re_path(r'^list/', views.UserListView.as_view(), name = 'list'), 
    re_path(r'^(?P<pk>[-\w]+)/delete/', views.DeleteUserView.as_view(), name = 'delete'),
 
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

templates/backend/includes/footer.html
<footer class="bg-white rounded shadow p-5 mb-4 mt-4">
    <div class="row">
        <div class="col-12 col-md-4 col-xl-6 mb-4 mb-md-0">
            <p class="mb-0 text-center text-lg-start">
                &copy; <a class="text-primary fw-normal" href="https://themesberg.com" target="_blank">siyamak1981@gmail.com</a>
                - My <a href="https://s-abasnezhad.ir" target="_blank">portfolio</a>.
            </p>
        </div>
        <div class="col-12 col-md-8 col-xl-6 text-center text-lg-start">
            <!-- List -->
            <ul class="list-inline list-group-flush list-group-borderless text-md-end mb-0">
                <li class="list-inline-item px-0 px-sm-2">
                    <a target="_blank" 
                       href="https://s-abasnezhad.ir">Django Dashboard</a>
                </li>
            </ul>
        </div>
    </div>
</footer>

templates/backend/includes/form.html
{% load form_tags widget_tweaks %}
 {% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
    <p {% if forloop.last %} class="mb-0" {% endif %}>{{ error }}</p>
        {% endfor %}
</div>
{% endif %}
{% for field in form %}
<div class="form-group">
    {{ field.label_tag }}
     {% render_field field class=field|input_class %}
    {% for error in field.errors %}
    <div class="invalid-feedback">
        {{ error }}
    </div>
    {% endfor %} 
{% if field.help_text %}
<small class="form-text text-muted">
    {{ field.help_text|safe }}
    </small>
{% endif %}
</div>

{% endfor %}

templates/backend/includes/nav_setting.html
<div class="table-settings mb-4">
    <div class="row align-items-center justify-content-between">
        <div class="col col-md-6 col-lg-3 col-xl-4">
            <div class="input-group me-2 me-lg-3 fmxw-400"><span class="input-group-text"><svg class="icon icon-xs"
                        x-description="Heroicon name: solid/search" xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd"
                            d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                            clip-rule="evenodd"></path>
                    </svg> </span><input type="text" class="form-control" placeholder="Search orders"></div>
        </div>

        <div class="col-4 col-md-2 col-xl-1 ps-md-0 text-end">
            <div class="dropdown"><button class="btn btn-link text-dark dropdown-toggle dropdown-toggle-split m-0 p-1"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><svg class="icon icon-md"
                        fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z"
                            clip-rule="evenodd"></path>
                    </svg> <span class="visually-hidden">Toggle Dropdown</span></button>
                <div class="dropdown-menu dropdown-menu-xs dropdown-menu-end pb-0" style=""><span
                        class="small ps-3 fw-bold text-dark">Show</span> <a
                        class="dropdown-item d-flex align-items-center fw-bold"
                        href="{% url 'tickets:my-tickets' %}">MyTicket <svg class="icon icon-xxs ms-auto"
                            fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                                clip-rule="evenodd"></path>
                        </svg></a><a class="dropdown-item fw-bold" href="{% url 'tickets:list' %}">Ticket List</a>
                    <a class="dropdown-item fw-bold rounded-bottom" href="{% url 'tickets:ticket_create' %}">Ticket
                        Create</a>

                </div>
            </div>
        </div>
    </div>
</div>

templates/backend/includes/navigation.html
<nav class="navbar navbar-top navbar-expand navbar-dashboard navbar-dark ps-0 pe-2 pb-0">
              <div class="container-fluid px-0">
                <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
                  <div class="d-flex align-items-center">
                    <!-- Search form -->
                    <form class="navbar-search form-inline" id="navbar-search-main">
                      <div class="input-group input-group-merge search-bar">
                          <span class="input-group-text" id="topbar-addon">
                            <svg class="icon icon-xs" x-description="Heroicon name: solid/search" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                              <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path>
                            </svg>
                          </span>
                          <input type="text" class="form-control" id="topbarInputIconLeft" placeholder="Search" aria-label="Search" aria-describedby="topbar-addon">
                      </div>
                    </form>
                    <!-- / Search form -->
                  </div>
                  <!-- Navbar links -->
                  <ul class="navbar-nav align-items-center">
                    <li class="nav-item dropdown">
                      <a class="nav-link text-dark notification-bell unread dropdown-toggle" data-unread-notifications="true" href="#" role="button" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                        <svg class="icon icon-sm text-gray-900" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z"></path></svg>
                      </a>
                      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-center mt-2 py-0">
                        <div class="list-group list-group-flush">
                          <a href="#" class="text-center text-primary fw-bold border-bottom border-light py-3">Notifications</a>
                          <a href="#" class="list-group-item list-group-item-action border-bottom">
                            <div class="row align-items-center">
                                <div class="col-auto">
                                  <!-- Avatar -->
                                  
                                  <img alt="Image placeholder" src="/static/assets/img/team/-picture-1.jpg" class="avatar-md rounded">
                                </div>
                                <div class="col ps-0 ms-2">
                                  <div class="d-flex justify-content-between align-items-center">
                                      <div>
                                        <h4 class="h6 mb-0 text-small">Jose Leos</h4>
                                      </div>
                                      <div class="text-end">
                                        <small class="text-danger">a few moments ago</small>
                                      </div>
                                  </div>
                                  <p class="font-small mt-1 mb-0">Added you to an event "Project stand-up" tomorrow at 12:30 AM.</p>
                                </div>
                            </div>
                          </a>
                          <a href="#" class="list-group-item list-group-item-action border-bottom">
                            <div class="row align-items-center">
                                <div class="col-auto">
                                  <!-- Avatar -->
                                  <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-2.jpg" class="avatar-md rounded">
                                </div>
                                <div class="col ps-0 ms-2">
                                  <div class="d-flex justify-content-between align-items-center">
                                      <div>
                                        <h4 class="h6 mb-0 text-small">Neil Sims</h4>
                                      </div>
                                      <div class="text-end">
                                        <small class="text-danger">2 hrs ago</small>
                                      </div>
                                  </div>
                                  <p class="font-small mt-1 mb-0">You've been assigned a task for "Awesome new project".</p>
                                </div>
                            </div>
                          </a>
                          <a href="#" class="list-group-item list-group-item-action border-bottom">
                            <div class="row align-items-center">
                                <div class="col-auto">
                                  <!-- Avatar -->
                                  <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-3.jpg" class="avatar-md rounded">
                                </div>
                                <div class="col ps-0 m-2">
                                  <div class="d-flex justify-content-between align-items-center">
                                      <div>
                                        <h4 class="h6 mb-0 text-small">Roberta Casas</h4>
                                      </div>
                                      <div class="text-end">
                                        <small>5 hrs ago</small>
                                      </div>
                                  </div>
                                  <p class="font-small mt-1 mb-0">Tagged you in a document called "Financial plans",</p>
                                </div>
                            </div>
                          </a>
                          <a href="#" class="list-group-item list-group-item-action border-bottom">
                            <div class="row align-items-center">
                                <div class="col-auto">
                                  <!-- Avatar -->
                                  <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-4.jpg" class="avatar-md rounded">
                                </div>
                                <div class="col ps-0 ms-2">
                                  <div class="d-flex justify-content-between align-items-center">
                                      <div>
                                        <h4 class="h6 mb-0 text-small">Joseph Garth</h4>
                                      </div>
                                      <div class="text-end">
                                        <small>1 d ago</small>
                                      </div>
                                  </div>
                                  <p class="font-small mt-1 mb-0">New message: "Hey, what's up? All set for the presentation?"</p>
                                </div>
                            </div>
                          </a>
                          <a href="#" class="list-group-item list-group-item-action border-bottom">
                            <div class="row align-items-center">
                                <div class="col-auto">
                                  <!-- Avatar -->
                                  <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-5.jpg" class="avatar-md rounded">
                                </div>
                                <div class="col ps-0 ms-2">
                                  <div class="d-flex justify-content-between align-items-center">
                                      <div>
                                        <h4 class="h6 mb-0 text-small">Bonnie Green</h4>
                                      </div>
                                      <div class="text-end">
                                        <small>2 hrs ago</small>
                                      </div>
                                  </div>
                                  <p class="font-small mt-1 mb-0">New message: "We need to improve the UI/UX for the landing page."</p>
                                </div>
                            </div>
                          </a>
                          <a href="#" class="dropdown-item text-center fw-bold rounded-bottom py-3">
                            <svg class="icon icon-xxs text-gray-400 me-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 12a2 2 0 100-4 2 2 0 000 4z"></path><path fill-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd"></path></svg>
                            View all
                          </a>
                        </div>
                      </div>
                    </li>
                    <li class="nav-item dropdown ms-lg-3">
                      <a class="nav-link dropdown-toggle pt-1 px-0" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <div class="media d-flex align-items-center">
                           <img src="{{ user.profile.get_avatar }}" class="avatar rounded-circle"  alt="Image placeholder" />
                          <div class="media-body ms-2 text-dark align-items-center d-none d-lg-block">
                            <span class="mb-0 font-small fw-bold text-gray-900">
                              Current User: <strong>{{ request.user.first_name }}</strong>
                            </span>
                          </div>
                        </div>
                      </a>
                      <div class="dropdown-menu dashboard-dropdown dropdown-menu-end mt-2 py-1">
                        <a class="dropdown-item d-flex align-items-center" href="{% url "user:create" %}">
                          <svg class="dropdown-icon text-gray-400 me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-6-3a2 2 0 11-4 0 2 2 0 014 0zm-2 4a5 5 0 00-4.546 2.916A5.986 5.986 0 0010 16a5.986 5.986 0 004.546-2.084A5 5 0 0010 11z" clip-rule="evenodd"></path></svg>
                          My Profile
                        </a>
                        <a class="dropdown-item d-flex align-items-center" href="{% url "dashboard:password_change" %}">
                          <svg class="dropdown-icon text-gray-400 me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-2 0c0 .993-.241 1.929-.668 2.754l-1.524-1.525a3.997 3.997 0 00.078-2.183l1.562-1.562C15.802 8.249 16 9.1 16 10zm-5.165 3.913l1.58 1.58A5.98 5.98 0 0110 16a5.976 5.976 0 01-2.516-.552l1.562-1.562a4.006 4.006 0 001.789.027zm-4.677-2.796a4.002 4.002 0 01-.041-2.08l-.08.08-1.53-1.533A5.98 5.98 0 004 10c0 .954.223 1.856.619 2.657l1.54-1.54zm1.088-6.45A5.974 5.974 0 0110 4c.954 0 1.856.223 2.657.619l-1.54 1.54a4.002 4.002 0 00-2.346.033L7.246 4.668zM12 10a2 2 0 11-4 0 2 2 0 014 0z" clip-rule="evenodd"></path></svg>
                          Change Password
                        </a>
                        <div role="separator" class="dropdown-divider my-1"></div>
                        <a class="dropdown-item d-flex align-items-center" href="{% url 'logout' %}">
                          <svg class="dropdown-icon text-danger me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>                
                          Logout
                        </a>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>

templates/backend/includes/scripts.html
{% load static %}
<script src="{% static "/assets/vendor/@popperjs/core/dist/umd/popper.min.js" %}"></script>
<script src="{% static "/assets/vendor/bootstrap/dist/js/bootstrap.min.js" %}"></script>

<!-- Vendor JS -->
<script src="{% static '/assets/vendor/onscreen/dist/on-screen.umd.min.js' %}"></script>

<!-- Slider -->
<script src="{% static '/assets/vendor/nouislider/distribute/nouislider.min.js' %}"></script>

<!-- Smooth scroll -->
<script src="{% static '/assets/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js' %}"></script>

<!-- Charts -->
<script src="{% static '/assets/vendor/chartist/dist/chartist.min.js' %}"></script>
<script src="{% static '/assets/vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js' %}"></script>

<!-- Datepicker -->
<script src="{% static '/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js' %}"></script>

<!-- Sweet Alerts 2 -->
<script src="{% static '/assets/vendor/sweetalert2/dist/sweetalert2.all.min.js' %}"></script>

<!-- Moment JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>

<!-- Vanilla JS Datepicker -->
<script src="{% static '/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js' %}"></script>

<!-- Notyf -->
<script src="{% static '/assets/vendor/notyf/notyf.min.js' %}"></script>

<!-- Simplebar -->
<script src="{% static '/assets/vendor/simplebar/dist/simplebar.min.js' %}"></script>

<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>

<!-- Volt JS -->
<script src="{% static '/assets/js/volt.js' %}"></script>

templates/backend/includes/settings-box.html
    <div class="theme-settings card bg-gray-800 pt-2 collapse" id="theme-settings">
        <div class="card-body bg-gray-800 text-white pt-4">
            <button type="button" class="btn-close theme-settings-close" aria-label="Close" data-bs-toggle="collapse"
                href="#theme-settings" role="button" aria-expanded="false" aria-controls="theme-settings"></button>
            <div class="d-flex justify-content-between align-items-center mb-3">
                <p class="m-0 mb-1 me-4 fs-7">write By siyamak<span role="img" aria-label="gratitude"><img src="https://img.icons8.com/plasticine/35/000000/edit.png"/></span></p>
                <a class="github-button" href="https://github.com/siyamak1981"
                    data-color-scheme="no-preference: dark; light: light; dark: light;" data-icon="octicon-star"
                    data-size="large" data-show-count="true"
                    aria-label="Star themesberg/volt-bootstrap-5-dashboard on GitHub">Star</a>
            </div>
          
        </div>
    </div>

    <div class="card theme-settings bg-gray-800 theme-settings-expand" id="theme-settings-expand">
        <div class="card-body bg-gray-800 text-white rounded-top p-3 py-2">
            <span class="fw-bold d-inline-flex align-items-center h6">
                <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd"></path></svg>
                Settings
            </span>
        </div>
    </div>